
# The `binning` keyword sets the light curve bin step duration.
# It is expressed in units of seconds. 
# Must be greater than zero.
binning: 0.1

# Data are filtered over one customizable energy band.
# The `energy_lims` keyword sets the low and high energy limit for this band.
# Energy limits are expressed in units of keV.
# The first value (the low energy limit) must be non negative and smaller
# than the second value (the high energy limit).
energy_lims:
- 20.0 # low energy limit
- 300.0 # high energy limit

# The `skip` keyword determines for how long the algorithm doesn't work
# after a trigger is encountered. This prevents re-trigger from long bursts
# with complex light curves or high variability.
# It is expressed in units of bin-steps. This means that if `binning` is set
# to 0.1 and `skip` is set to 3000, the algorithm won't work for the 5 minutes
# which follow a trigger. Passed the skip time, the algorithm is restarted.
# Must be a non-negative integer.
skip: 3000


algorithm_params:
 # The `threshold` keyword sets the confidence level for detection.
 # The higher the threshold, the less false positive but the more false negative.
 # The threshold is expressed in units of standard deviations.
 # Must be greater than 0.
 threshold: 5.5

 # The `mu_min` key seta focus parameter for killing old changepoints 
 # which most likely will never result in a trigger. Keep it below 1.5.
 # Must be greater than 1.
 mu_min: 1.1
 # The `alpha` keyword sets the background smoothing characteristic time  	au,
 # 	au = (binning/0.005).
 # Must be greater than 0.
 alpha: 0.005
 
 # The `beta` keyword sets the trend component for background estimate.
 # The algorithm may become unstable when `beta` is set: leave it `0.0` unless
 # you have good reasons to use it.
 # Must be greater than 0.
 beta: 0.0
 
 # The `m` keyword will prevent the most recent observed count to be used for 
 # background estimation. This prevents background estimate to be "polluted"
 # by real transients. 
 # It is expressed in units of bin-steps. This means that if `binning` is set
 # to 0.1 and `m` is set to 40, the algorithm won't work use the latest 4.0 s
 # of data in background estimate. 
 # Must be a non-negative integer.
 m: 40
 
 # The `t_max` parameter tells the algorithm to kill old changepoint.
 # It is a good idea to keep it equal to `m`. Also expressed as a bin-step.
 # Must be an integer greater than 0.
 t_max: 40
 
 # The algorithms stays idle for a while before startin its operations.
 # This help forming a good estimate of the background. 
 # The `sleep` parameters sets for how long this idle period lasts.
 # The `sleep` parameter is expressed as a bin-step.
 # Must be an integer greater than `m` or `null` (sets to `m+1`).
 sleep: 41
